name: 'Terraform GitHub Actions'
on:
  push:
    branches:
      - main
jobs:
  terraform:
    name: 'Terraform-CICD-Pipeline'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: terraform
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.7
        terraform_wrapper: false
    - run: echo "fmt"
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
    - run: echo "init"
    - name: Terraform Init
      id: init
      run: terraform init
    - run: echo "validate"
    - name: Terraform Validate
      id: validate
      run: terraform validate
    - run: echo "plan"
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
    - run: echo "apply"
    - name: Terraform Apply
      run: terraform apply -auto-approve
